/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package number.identifier;

/**
 *
 * @author prajwol
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
    }
void find_whatNoIs(){

        String inputted_number;
        inputted_number=entered_number.getText();
       
        
        // convert the given string to array
        
        int[] arr_number = new int[inputted_number.length()];
        for (int i = 0; i < inputted_number.length(); i++) {
        arr_number[i] = inputted_number.charAt(i) - '0';  // Convert char to int
        }
        
        //Logic to chcek what no::
     if (arr_number.length==10) {
           if (arr_number[0] == 9) {

            if (arr_number[1] == 8) {
                if (arr_number[2] == 4 || arr_number[2] == 5 || arr_number[2] == 6) {
                    output_text.setText("Given Number is NTC number");
                }
                if (arr_number[2] == 0 || arr_number[2] == 1 || arr_number[2] == 2) {
                    output_text.setText("Given Number is NCELL number");
                   
                }
                if (arr_number[2] == 8) {
                    
                    output_text.setText("Given Number is Smart Cell number number");
                    
                }
            }

            if (arr_number[1] == 7) {

                if (arr_number[2] == 4 || arr_number[2] == 5 || arr_number[2] == 6) {
                    output_text.setText("Given Number is NTC number");
                    
                }
                if (arr_number[2] == 2) {
                    output_text.setText("Given Number is UTL number");
                    
                }
            }
            if (arr_number[1] == 6) {
                if (arr_number[2] == 1 || arr_number[2] == 2) {
                    output_text.setText("Given Number is Smart Cell number number");
                   
                }
                if (arr_number[2] == 3) {
                    output_text.setText("Given Number is Hello Mobile number");
                    
                }
            }

        }else{
           output_text.setText("Given Number is Invalid Number . ");
           }
    }else{
     output_text.setText("Given Number is Invalid Number . ");
     }
        
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        output_text = new javax.swing.JLabel();
        entered_number = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        output_text1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(44, 98, 189));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 430, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 430, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 430, 10));

        jPanel2.setBackground(new java.awt.Color(97, 170, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        output_text.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 24)); // NOI18N
        output_text.setForeground(new java.awt.Color(253, 174, 42));
        output_text.setText("Given number is :");
        jPanel2.add(output_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 720, 30));

        entered_number.setBackground(new java.awt.Color(44, 98, 189));
        entered_number.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 11)); // NOI18N
        entered_number.setForeground(new java.awt.Color(255, 255, 255));
        entered_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entered_numberActionPerformed(evt);
            }
        });
        jPanel2.add(entered_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 360, 30));

        jLabel3.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(253, 174, 42));
        jLabel3.setText("Enter Phone number :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 350, 30));

        output_text1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 8)); // NOI18N
        output_text1.setForeground(new java.awt.Color(255, 255, 255));
        output_text1.setText("(Make sure you enter a Nepal Number of 10 digits )Supported Numbers: Ncell/Ntc/UTL/HELLO/Smartcell. ----Made By Prajwol Chand ");
        jPanel2.add(output_text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 700, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 830, 260));

        jLabel2.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Phone number Identifier");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 590, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entered_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entered_numberActionPerformed
        // TODO add your handling code here:
       find_whatNoIs();
        
    }//GEN-LAST:event_entered_numberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField entered_number;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel output_text;
    private javax.swing.JLabel output_text1;
    // End of variables declaration//GEN-END:variables
}
